---
- name: install apache2 and php
  hosts: all
  become: yes
  tasks: 
    - name: Install apache httpd
      apt:
        name: apache2
        state: 
    - name: Install php
      apt:
        name: php
        state: present
  