---
- name: Install tomcat9
  hosts: all
  become: yes
  tasks:
    - name: install openjdk-11-jdk
      apt:
        name: tomcat9
        update_cache: yes
        state: present
    - name: tomcat
      ansible.builtin.user:
        name: tomcat
        shell: /bin/false
        home: /opt/tomcat/
    - name: Download tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz
        dest: /opt/tomcat/
          
   