---
- name: Install tomcat9
  hosts: all
  become: yes
  tasks:
    - name: install openjdk-11-jdk
      apt:
        name: tomcat9
        update_cache: yes
        state: present
    - name: tomcat
      ansible.builtin.user:
        name: tomcat
        shell: /bin/false
        state: present
    - name: Download tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.56/bin/apache-tomcat-9.0.56.tar.gz"
        dest: "/tmp/apache-tomcat-9.0.56.tar.gz"
    - name: create directory
      file:
        path: /opt/tomcat
        state: directory
    - name: Extract tar file
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-9.0.56.tar.gz"
        dest: /opt/tomcat/
        mode: 0755
        remote_src: yes
    - name: Create a symbolic link
      ansible.builtin.file:
        src: "/opt/tomcat/apache-tomcat-9.0.56"
        dest: /opt/tomcat/latest
        state: link
    - name: Create recurse file
      ansible.builtin.file:
        dest: /opt/tomcat/
        owner: tomcat
        group: tomcat
        state: directory
        recurse: yes
    - name: find all the shell files in the binaries
      find: 
        path: tomcat/latest/bin
        pattern: "*.sh"
      register: shfiles
    - set_fact:
        tomcat_executables: "{{ shfiles.files | map(attribute='path') | list }}"
    - name: change permission of shell files
      file:
        path: "{{ item }}"
        mode: 0751
      with_items: D:\ansible\activity\tomcat.service
    - name: tomcat service
      copy: 
        src: tomcat.service
        state: started